### ISSUE TITLE
支付宝会扫码出现异常

### ISSUE THREAD

**Issue by 17606677790** [thlws/payment-thl#1]
使用的版本1.1.2
大量使用支付宝扫码支付的时候偶尔会出现报错,BeanUtils.copyProperties是这个地方造成的吗?

org.apache.commons.beanutils.ConversionException: No value specified for 'Date'
at org.apache.commons.beanutils.converters.AbstractConverter.handleMissing(AbstractConverter.java:310)
at org.apache.commons.beanutils.converters.AbstractConverter.convert(AbstractConverter.java:136)
at org.apache.commons.beanutils.converters.ConverterFacade.convert(ConverterFacade.java:60)
at org.apache.commons.beanutils.BeanUtilsBean.convert(BeanUtilsBean.java:1078)
at org.apache.commons.beanutils.BeanUtilsBean.copyProperty(BeanUtilsBean.java:437)
at org.apache.commons.beanutils.BeanUtilsBean.copyProperties(BeanUtilsBean.java:286)
at org.thlws.payment.alipay.core.AlipayCore.pay(AlipayCore.java:369)
at org.thlws.payment.AlipayClient.pay(AlipayClient.java:96)

**Comment by thlws** [comment]
v1.1.3 中已修复
